FROM --platform=$BUILDPLATFORM rust:1.70-slim-bullseye as build

COPY Cargo.toml .
COPY Cargo.lock .
COPY src src

RUN RUSTFLAGS='-C target-feature=+crt-static' cargo build --release

FROM scratch

COPY --from=build /target/wasm32-wasi/release/wasm-on-docker /native

ENTRYPOINT [ "native" ]