spin_manifest_version = "1"
authors = ["shinyay <shinya.com@gmail.com>"]
description = "spin new http-rust my-logging-app"
name = "my-logging-app"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[variables]
loglevel = { required = true }

[[component]]
id = "my-logging-app"
source = "target/wasm32-wasi/release/my_logging_app.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
[component.config]
loglevel = "{{ loglevel }}"