[package]
name = "http-call-sample"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest_wasi = { version = "0.11.15", features = ["json"] }
serde = { version = "1.0.167", features = ["derive"] }
tokio_wasi = { version = "1.25.2", features = ["rt", "macros"] }
